# Generated by Django 5.1.7 on 2025-03-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('por_realizar', 'Por realizar'), ('en_transito', 'En tránsito'), ('completada', 'Completada')], default='por_realizar', max_length=20)),
            ],
        ),
    ]
